project_name: go-build-test
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  -
    main: .
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
